---
title: "2020 Consumer Complaints Data"
author: "Jack Wild"
date: "4/19/2022"
output:
  flexdashboard::flex_dashboard:
    theme: united
    orientation: rows
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse) #includes ggplot2
library(janitor) 
library(scales)
library(lubridate)
library(ggthemes)
library(dplyr)

complaints <- read_rds("complaints.rds")

head(complaints)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Type of products receiving the most complaints

```{r}

head(complaints %>% count(sub_product, sort = TRUE))

```

Column {data-width=500}
-----------------------------------------------------------------------

### Companies that failed to provide timely responses to compaints


```{r}

complaints_responses <- head(complaints %>% filter(timely_response == "No") %>% 
  count(company, sort = TRUE))

complaints_responses

```

### States with the most complaints {data-height=800}

```{r}

complaints_states <- head(complaints %>% count(state, sort = TRUE))


ggplot(complaints_states , aes(x=state , y=n, width=.25)) + geom_bar(stat="identity", color="#9ebcda", fill= "#9ebcda") +
  scale_y_discrete(name="Number of Complaitns") +
  scale_x_discrete(name="States") +
  labs(title = " ", 
       caption = "By Jack Wild") +
  geom_text(stat="identity", label=complaints_states$n, vjust= 1, size=3)

```

